-- Create Tenants Table
CREATE TABLE tenants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug VARCHAR(255) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    status VARCHAR(255),
    branding_s3_key VARCHAR(255),
    plan VARCHAR(255),
    metadata_json JSONB,
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

-- Create User Table
CREATE TABLE app_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL,
    password VARCHAR(100) NOT NULL,
    role VARCHAR(20),
    tenant_id BIGINT,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    CONSTRAINT fk_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id)
);

-- Add unique constraint to email
CREATE UNIQUE INDEX idx_user_email ON app_user(email);

-- Seed default tenant
INSERT INTO tenants (slug, name, status, plan, created_at, updated_at) 
VALUES ('main', 'Default Tenant', 'ACTIVE', 'FREE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);