import { useState, useEffect } from 'react'
import { Link } from 'react-router-dom'
import { Button, Badge, Spinner } from 'flowbite-react'
import NavBar from '../components/NavBar'
import Hero from '../components/Hero'
import Footer from '../components/Footer'
import { billingAPI } from '../services/apiServices'
import {
  HiCheckCircle,
  HiChatAlt2,
  HiChartBar,
  HiLightningBolt,
  HiCurrencyDollar,
  HiShieldCheck,
  HiUserGroup,
  HiSparkles,
  HiPhone,
} from 'react-icons/hi'

const features = [
  {
    icon: HiLightningBolt,
    title: 'Easy survey builder',
    description: 'Create multi-channel surveys (Web, SMS, USSD, Mobile) in minutes with an intuitive drag-and-drop builder.',
  },
  {
    icon: HiCurrencyDollar,
    title: 'Built-in reward system',
    description: 'Attach airtime, cash, or loyalty rewards to surveys. Participants are paid instantly via M-Pesa or Paystack.',
  },
  {
    icon: HiChartBar,
    title: 'AI-powered insights',
    description: 'Get boardroom-ready reports generated by AI — key findings, recommendations, and respondent clusters.',
  },
  {
    icon: HiUserGroup,
    title: 'Referral engine',
    description: 'Run ODPC-compliant referral campaigns. Closed or open groups, SMS-based opt-in, automated reward triggers.',
  },
  {
    icon: HiShieldCheck,
    title: 'Performance evaluations',
    description: 'Assess individuals or teams with scored surveys, weighted questions, and category breakdowns.',
  },
  {
    icon: HiChatAlt2,
    title: 'Decision intelligence',
    description: 'Turn survey data into action plans. Track progress from insight to outcome in one place.',
  },
]

const FALLBACK_PLANS = [
  {
    id: 'basic',
    name: 'Basic',
    price: 2999,
    billingInterval: 'MONTHLY',
    features: JSON.stringify({
      isCustomPricing: false,
      displayFeatures: [
        'Up to 10 surveys',
        '500 responses per survey',
        'Web & SMS channels',
        'Basic analytics dashboard',
        'Email support',
      ],
    }),
  },
  {
    id: 'pro',
    name: 'Pro',
    price: 7999,
    billingInterval: 'MONTHLY',
    features: JSON.stringify({
      isCustomPricing: false,
      displayFeatures: [
        'Up to 50 surveys',
        '5,000 responses per survey',
        'All channels (Web, SMS, USSD, Mobile)',
        'AI-powered insights & reports',
        'Referral engine',
        'Performance evaluations',
        'Priority support',
      ],
    }),
  },
  {
    id: 'enterprise',
    name: 'Enterprise',
    price: 0,
    billingInterval: 'MONTHLY',
    features: JSON.stringify({
      isCustomPricing: true,
      displayFeatures: [
        'Unlimited surveys',
        'Unlimited responses',
        'All channels + API access',
        'Advanced AI insights & custom reports',
        'Full referral & decision intelligence',
        'Outbound webhooks & integrations',
        'Dedicated account manager & SLA',
      ],
    }),
  },
]

const PricingCard = ({ plan, isPopular }) => {
  let parsed = {}
  try {
    parsed = JSON.parse(plan.features)
  } catch { /* ignore parse errors */ }

  const isCustom = parsed.isCustomPricing === true
  const displayFeatures = parsed.displayFeatures || []
  const interval = plan.billingInterval === 'YEARLY' ? 'yr' : 'mo'

  return (
    <div className={`relative flex flex-col rounded-2xl border-2 p-8 ${
      isPopular
        ? 'border-primary-500 bg-primary-50 shadow-2xl scale-105'
        : 'border-gray-200 bg-white shadow-md'
    }`}>
      {isPopular && (
        <div className="absolute -top-4 left-1/2 -translate-x-1/2">
          <Badge color="purple" className="px-4 py-1 text-sm font-semibold">
            <HiSparkles className="inline w-3.5 h-3.5 mr-1" />
            Most Popular
          </Badge>
        </div>
      )}

      <h3 className="text-xl font-bold text-gray-900">{plan.name}</h3>

      <div className="mt-4 mb-6">
        {isCustom ? (
          <div>
            <span className="text-3xl font-extrabold text-gray-900">Custom</span>
            <p className="text-sm text-gray-500 mt-1">Tailored to your scale</p>
          </div>
        ) : (
          <div>
            <span className="text-sm font-medium text-gray-500">KES </span>
            <span className="text-4xl font-extrabold text-gray-900">
              {Number(plan.price).toLocaleString()}
            </span>
            <span className="text-gray-500 text-sm">/{interval}</span>
          </div>
        )}
      </div>

      <ul className="space-y-3 flex-grow mb-8">
        {displayFeatures.map((feat, i) => (
          <li key={i} className="flex items-start gap-2 text-sm text-gray-700">
            <HiCheckCircle className="w-5 h-5 text-green-500 shrink-0 mt-0.5" />
            <span>{feat}</span>
          </li>
        ))}
      </ul>

      {isCustom ? (
        <a href="mailto:sales@suresurvey.co" className="block">
          <Button color="dark" className="w-full">
            <HiPhone className="w-4 h-4 mr-2" />
            Contact Sales
          </Button>
        </a>
      ) : (
        <Button
          as={Link}
          to="/signup"
          color={isPopular ? 'purple' : 'light'}
          className={`w-full ${isPopular ? 'font-bold' : ''}`}
        >
          Get Started
        </Button>
      )}
    </div>
  )
}

const Home = () => {
  const [plans, setPlans] = useState([])
  const [plansLoading, setPlansLoading] = useState(true)

  useEffect(() => {
    billingAPI.getAllPlans()
      .then((res) => setPlans(res.data || []))
      .catch(() => setPlans(FALLBACK_PLANS))
      .finally(() => setPlansLoading(false))
  }, [])

  const displayPlans = plans.length >= 3 ? plans : FALLBACK_PLANS

  return (
    <div className="min-h-screen flex flex-col">
      <NavBar />

      <main className="flex-grow">
        <Hero />

        {/* Features */}
        <section className="py-20 bg-white">
          <div className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8">
            <div className="text-center mb-14">
              <h2 className="text-3xl font-bold text-gray-900">Everything you need to collect better data</h2>
              <p className="mt-4 text-lg text-gray-500 max-w-2xl mx-auto">
                From survey creation to actionable intelligence — built for African enterprises.
              </p>
            </div>
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
              {features.map((f) => (
                <div key={f.title} className="flex items-start gap-4 p-6 rounded-xl border border-gray-100 hover:shadow-md transition-shadow">
                  <div className="flex-shrink-0 w-10 h-10 rounded-lg bg-primary-100 flex items-center justify-center">
                    <f.icon className="w-5 h-5 text-primary-600" />
                  </div>
                  <div>
                    <h3 className="font-semibold text-gray-900 mb-1">{f.title}</h3>
                    <p className="text-sm text-gray-500 leading-relaxed">{f.description}</p>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* Pricing */}
        <section className="py-20 bg-gray-50">
          <div className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8">
            <div className="text-center mb-14">
              <h2 className="text-3xl font-bold text-gray-900">Simple, transparent pricing</h2>
              <p className="mt-4 text-lg text-gray-500">
                Start free. Scale as you grow. No hidden fees.
              </p>
            </div>

            {plansLoading ? (
              <div className="flex justify-center py-12">
                <Spinner size="xl" />
              </div>
            ) : (
              <div className="grid grid-cols-1 md:grid-cols-3 gap-8 items-center">
                {displayPlans.map((plan) => (
                  <PricingCard
                    key={plan.id}
                    plan={plan}
                    isPopular={plan.name === 'Pro'}
                  />
                ))}
              </div>
            )}

            <p className="text-center text-sm text-gray-400 mt-10">
              All plans include a 14-day free trial. No credit card required.
            </p>
          </div>
        </section>

        {/* CTA */}
        <section className="py-20 bg-primary-600">
          <div className="max-w-3xl mx-auto px-4 text-center">
            <h2 className="text-3xl font-bold text-white">Ready to start collecting insights?</h2>
            <p className="mt-4 text-primary-100 text-lg">
              Join hundreds of organisations using Sure Survey to make data-driven decisions.
            </p>
            <div className="mt-10 flex flex-col sm:flex-row gap-4 justify-center">
              <Button as={Link} to="/signup" size="xl" color="light" className="font-semibold px-8">
                Create free account
              </Button>
              <Button as={Link} to="/login" size="xl" color="purple" className="font-semibold px-8">
                Sign in
              </Button>
            </div>
          </div>
        </section>
      </main>

      <Footer />
    </div>
  )
}

export default Home
