package com.survey_engine.business_integration.models;

import com.survey_engine.business_integration.config.security.AttributeEncryptor;
import com.survey_engine.business_integration.models.enums.BusinessIntegrationType;
import com.survey_engine.common.models.BaseEntity;
import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;

import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

/**
 * Stores configuration for a business integration (e.g., M-Pesa Paybill).
 */
@EqualsAndHashCode(callSuper = true)
@Entity
@Table(name = "business_integrations")
@Data
@NoArgsConstructor
@AllArgsConstructor
public class BusinessIntegration extends BaseEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private UUID id;

    @Column(nullable = false)
    private String businessName;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private BusinessIntegrationType type;

    @Column(name = "survey_id", nullable = false)
    private Long surveyId;

    // --- M-Pesa Specific Config ---
    @Column(name = "shortcode")
    private String shortcode; // Paybill or Till Number

    // Optional: Encrypted credentials if user wants us to register URLs for them
    @Column(name = "consumer_key")
    @Convert(converter = AttributeEncryptor.class)
    private String consumerKey;

    @Column(name = "consumer_secret")
    @Convert(converter = AttributeEncryptor.class)
    private String consumerSecret;

    // --- Security ---
    @Column(name = "callback_secret_token", nullable = false)
    private String callbackSecretToken; // Generated by us to secure the webhook

    @Column(name = "is_active")
    private boolean isActive = true;

    @OneToMany(mappedBy = "integration", cascade = CascadeType.ALL, orphanRemoval = true)
    private List<BusinessTransaction> transactions = new ArrayList<>();
}