spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://127.0.0.1:8080

safaricom:
  api:
    url: ${SAFARICOM_API_URL}

logging:
  level:
    root: INFO
    com.user_service.user_service: DEBUG