spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://127.0.0.1:8080

app-security:
  base-url: ${APP_BASE_URL}
  encryption:
    password: ${APP_ENCRYPTION_PASSWORD}
    salt: ${APP_ENCRYPTION_SALT}

daraja:
  api:
    base-url: https://api.safaricom.co.ke

logging:
  level:
    root: INFO
    com.user_service.user_service: DEBUG