server:
  port: 8082

# Put all database properties in main .yaml file
spring:
  application:
    name: payments
  datasource:
    url: jdbc:postgresql://localhost:${SURE_SURVEY_PAYMENT_PORT}/${SURE_SURVEY_PAYMENT_DB}
    username: ${SURE_SURVEY_PAYMENT_ADMIN}
    password: ${SURE_SURVEY_PAYMENT_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 10
      idle-timeout: 10000
      max-lifetime: 600000

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
    show-sql: false

  flyway:
    locations: classpath:db/migration
    baseline-on-migrate: true
    enabled: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://127.0.0.1:8080
  data:
    redis:
      port: 6379
      host: localhost

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

logging:
  level:
    root: INFO
    com.payments.payments: DEBUG