server:
  port: 8081

# Put all database properties in main .yaml file
spring:
  application:
    name: survey
  datasource:
    url: jdbc:postgresql://localhost:${SURE_SURVEY_ENGINE_PORT}/${SURE_SURVEY_ENGINE_DB}
    username: ${SURE_SURVEY_ENGINE_ADMIN}
    password: ${SURE_SURVEY_ENGINE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 10
      idle-timeout: 10000
      max-lifetime: 600000

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
    show-sql: false

  flyway:
    locations: classpath:db/migration
    baseline-on-migrate: true
    enabled: true
    # Specifies the schema for Flyway to manage its history table.
    # This is necessary to avoid permission errors on the default 'public' schema.
    schemas: survey_service

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://127.0.0.1:8080
  data:
    redis:
      port: 6379
      host: localhost

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

logging:
  level:
    root: INFO
    com.survey.survey: DEBUG
