
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://127.0.0.1:8080
  data:
    redis:
      port: 6379
      host: localhost

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    publisher-confirm-type: correlated
    publisher-returns: true

logging:
  level:
    root: INFO
    com.survey.survey: DEBUG
