server:
  port: 8080

# Put all database properties in main .yaml file
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:${SURE_SURVEY_USER_DB_PORT}/${SURE_SURVEY_USER_DB}
    username: ${SURE_SURVEY_USER_DB_ADMIN}
    password: ${SURE_SURVEY_USER_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    user: ${SURE_SURVEY_USER_DB_ADMIN}
    password: ${SURE_SURVEY_USER_DB_PASSWORD}
    url: jdbc:postgresql://localhost:${SURE_SURVEY_USER_DB_PORT}/${SURE_SURVEY_USER_DB}
    baseline-on-migrate: true
    enabled: true

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_SHORT_EXPIRATION}

logging:
  level:
    root: INFO
    com.user_service.user_service: DEBUG